services:
  bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ${HOST_DATA_DIR:-./data}:/app/data
      - ${HOST_TMP_DIR:-./tmp}:/app/tmp
      - ${HOST_PUBLIC_IMAGE_DIR:-./public-images}:/app/public-images
    restart: unless-stopped
