services:
  bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./tmp:/app/tmp
      - ./public-images:/app/public-images
    restart: unless-stopped
